#!/usr/bin/env bash
# Refresh the generated inventory section of THIRD_PARTY_NOTICES.md.
# Curated license texts in that file remain authoritative; this script
# appends/updates a machine inventory when cargo/flutter tools are available.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/apps/client/assets/legal/THIRD_PARTY_NOTICES.generated.md"
MARK_START="<!-- BEGIN GENERATED INVENTORY -->"
MARK_END="<!-- END GENERATED INVENTORY -->"

mkdir -p "$(dirname "$OUT")"

{
  echo "# Generated dependency inventory"
  echo
  echo "Generated by scripts/generate_third_party_notices.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)."
  echo "This file is informational. See THIRD_PARTY_NOTICES.md for required texts."
  echo
  echo "## Rust (Cargo.lock)"
  echo
  if command -v cargo >/dev/null 2>&1; then
    if cargo metadata --format-version 1 --manifest-path "$ROOT/Cargo.toml" >"$ROOT/target/cargo-metadata-notices.json" 2>/dev/null; then
      python3 - "$ROOT/target/cargo-metadata-notices.json" <<'PY'
import json, sys
from collections import defaultdict
m = json.load(open(sys.argv[1]))
by = defaultdict(list)
for p in m["packages"]:
    if p["name"].startswith("helmhost-"):
        continue
    lic = p.get("license") or "(none / see crate)"
    by[lic].append("%s %s" % (p["name"], p["version"]))
for lic in sorted(by, key=lambda x: (-len(by[x]), x)):
    print("### %s" % lic)
    print()
    for n in sorted(by[lic]):
        print("- %s" % n)
    print()
PY
    else
      echo "_cargo metadata failed (network/offline). Using package names from Cargo.lock._"
      echo
      python3 - "$ROOT/Cargo.lock" <<'PY'
import re, sys
text = open(sys.argv[1]).read()
pkgs = re.findall(r'^name = "([^"]+)"\nversion = "([^"]+)"', text, re.M)
for n, v in sorted(pkgs):
    if n.startswith("helmhost-"):
        continue
    print("- %s %s" % (n, v))
PY
    fi
  else
    echo "_cargo not available_"
  fi
  echo
  echo "## Dart (pubspec.lock direct + transitive names)"
  echo
  if [[ -f "$ROOT/apps/client/pubspec.lock" ]]; then
    python3 - "$ROOT/apps/client/pubspec.lock" <<'PY'
import re, sys
text = open(sys.argv[1]).read()
pkgs = re.findall(r'^  ([a-zA-Z0-9_]+):\n(?:    .*\n)*?    version: "([^"]+)"', text, re.M)
for n, v in sorted(pkgs):
    if n in ("flutter", "flutter_test", "sky_engine", "flutter_web_plugins"):
        continue
    print("- %s %s" % (n, v))
PY
  else
    echo "_pubspec.lock missing_"
  fi
} >"$OUT"

echo "Wrote $OUT"
echo "Merge into THIRD_PARTY_NOTICES.md manually or paste between:"
echo "  $MARK_START"
echo "  $MARK_END"
